#!/bin/bash

set -e
set -x

cd /tmp

echo "Installing sbt $SBT_VERSION..."
mkdir -p "/usr/local/sbt"
wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | tar xz -C /usr/local/sbt --strip-components=1
export PATH="/usr/local/sbt/bin:$PATH"
sbt sbtVersion
echo "sbt $SBT_VERSION installed"

cd ..