#!/bin/bash

set -e
set -x

cd /tmp

echo "Installing Spark ${SPARK_VERSION}..."
wget --no-verbose http://apache.mirror.iphh.net/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
tar -xvzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark
rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
echo "Spark ${SPARK_VERSION} installed"

cd ..