#!/bin/bash

set -e
set -x

cd /tmp

echo 'Installing Python 3...'
wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
tar -xf Python-3.7.9.tgz
cd Python-3.7.9
# ./configure --enable-optimizations
./configure
make -j
make -j altinstall
update-alternatives --install "/usr/bin/python" "python" "$(which python3.7)" 1
apt install -y python3-pip
cd ..
echo 'Python 3 installed'

cd ..