#!/bin/bash

set -e

[ ! -z "$DEPLOY_BASE" ] && docker build -t tonydc/spark-base:2.4.7 ./docker/base || true
docker build -t tonydc/spark-master:2.4.7 ./docker/master
docker build -t tonydc/spark-worker:2.4.7 ./docker/worker
docker build -t tonydc/spark-submit:2.4.7 ./docker/submit

