#!/bin/bash

set -e
set -x

export SPARK_MASTER_HOST=`hostname`
export SPARK_HOME="/opt/spark"

. "/opt/spark/bin/load-spark-env.sh"
. "/opt/spark/sbin/spark-config.sh"

mkdir -p $SPARK_MASTER_LOG
ln -sf /dev/stdout $SPARK_MASTER_LOG/spark-master.out

/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master \
    --ip $SPARK_MASTER_HOST \
    --port $SPARK_MASTER_PORT \
    --webui-port $SPARK_MASTER_WEBUI_PORT >> $SPARK_MASTER_LOG/spark-master.out
